-- begin ENTITYVIEWSSAMPLE_DEPARTMENT
alter table ENTITYVIEWSSAMPLE_DEPARTMENT add constraint FK_ENTITYVIEWSSAMPLE_DEPARTMENT_ON_MANAGER foreign key (MANAGER_ID) references ENTITYVIEWSSAMPLE_EMPLOYEE(ID)^
create unique index IDX_ENTITYVIEWSSAMPLE_DEPARTMENT_UNIQ_NAME on ENTITYVIEWSSAMPLE_DEPARTMENT (NAME) ^
create index IDX_ENTITYVIEWSSAMPLE_DEPARTMENT_ON_MANAGER on ENTITYVIEWSSAMPLE_DEPARTMENT (MANAGER_ID)^
-- end ENTITYVIEWSSAMPLE_DEPARTMENT
-- begin ENTITYVIEWSSAMPLE_EMPLOYEE
alter table ENTITYVIEWSSAMPLE_EMPLOYEE add constraint FK_ENTITYVIEWSSAMPLE_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ENTITYVIEWSSAMPLE_DEPARTMENT(ID)^
create index IDX_ENTITYVIEWSSAMPLE_EMPLOYEE_ON_DEPARTMENT on ENTITYVIEWSSAMPLE_EMPLOYEE (DEPARTMENT_ID)^
-- end ENTITYVIEWSSAMPLE_EMPLOYEE
